Add integration test to validate `base-url`

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -248,3 +248,54 @@ jobs:
           done <<< "$tests"
 
           echo $'\u2705 Test passed' | tee -a $GITHUB_STEP_SUMMARY
+
+  test-base-url:
+    name: 'Integration test: base-url option'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: ./.github/actions/install-dependencies
+      - id: base-url-default
+        name: Default base-url not set
+        uses: ./
+        with:
+          script: |
+            const endpoint = github.request.endpoint
+            return endpoint({}).url
+          result-encoding: string
+      - id: base-url-set
+        name: base-url set
+        uses: ./
+        with:
+          base-url: https://my.github-enterprise-server.com/api/v3
+          script: |
+            const endpoint = github.request.endpoint
+            return endpoint({}).url
+          result-encoding: string
+      - id: base-url-env
+        name: base-url does not override GITHUB_API_URL when not set
+        uses: ./
+        env:
+          GITHUB_API_URL: https://my.github-enterprise-server.com/api/v3
+        with:
+          script: |
+            const endpoint = github.request.endpoint
+            return endpoint({}).url
+          result-encoding: string
+      - run: |
+          echo "- Validating base-url default"
+          expected="https://api.github.com"
+          if [[ "${{steps.base-url-default.outputs.result}}" != "$expected" ]]; then
+            echo $'::error::\u274C' "Expected base-url to start with '$expected', got ${{steps.base-url-default.outputs.result}}"
+            exit 1
+          fi
+          echo "- Validating base-url set to a value"
+          expected="https://my.github-enterprise-server.com/api/v3"
+          if [[ "${{steps.base-url-set.outputs.result}}" != "$expected" ]]; then
+            echo $'::error::\u274C' "Expected base-url to start with '$expected', got ${{steps.base-url-set.outputs.result}}"
+            exit 1
+          fi
+          echo "- Validating base-url not set respects GITHUB_API_URL"
+          expected="https://my.github-enterprise-server.com/api/v3"
+          if [[ "${{steps.base-url-env.outputs.result}}" != "$expected" ]]; then
+            echo $'::error::\u274C' "Expected base-url to start with '$expected', got ${{steps.base-url-env.outputs.result}}"
